[font]
size = 10.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
option_as_alt = "OnlyLeft"

[[keyboard.bindings]]
key = "+"
mods = "Control|Shift"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "_"
mods = "Control|Shift"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "("
mods = "Control|Shift"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "Equals"
mods = "Control"
action = "None"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "None"
